### ISSUE TITLE
Fossa Mail support

### ISSUE THREAD

**Issue by beerisgood** [SecUSo/torpedo#1]
Can you please add Fossa Mail support?
I try to install your addon but the install fails. Then i chance the install.rdf to allow versions below 26 and the install works, but only the welcome screen works and not the addon itself.

http://www.fossamail.org
https://github.com/MoonchildProductions/FossaMail

**Comment by beerisgood** [comment]
_push_

**Comment by beerisgood** [comment]
_push_

**Comment by bettyballin** [comment]
Sorry for the inconvenience, but we currently don't plan to add Fossa Mail support.

**Comment by beerisgood** [comment]
The addon works with latest FossaMail (v27) !
