### ISSUE TITLE
Look up the domain with Google does not work correctly

### ISSUE THREAD

**Issue by floomue** [SecUSo/torpedo#12]
In [Line  #593](https://github.com/SecUSo/torpedo/blob/master/background.js#L593) the domain is passed with an incorrect parameter in the URL.
Can be fixed by changing `"http://google.de/#q="` to `"http://google.de/?q="`

Or, I don't know if this works in the Thunderbird addon, if you also pass "search", the request is executed directly. `"http://www.google.de/search?q="`

**Comment by lauraimler** [comment]
Thanks for noticing. Corrected in the commit `355634672cf6df54f6002667366f931c97b94087`.
