### ISSUE TITLE
Torpedo 3.0.1 loses settings during Thunderbird update

### ISSUE THREAD

**Issue by d4k0** [SecUSo/torpedo#13]
I noticed that Torpedo (3.0.1) loses its settings when Thunderbird is updated. I have experienced this behavior with Thunderbird 78.x and 91.x. Could you please fix this?

**Comment by philheller** [comment]
Thank you for your notification.
We are currently looking into the issue.

**Comment by philheller** [comment]
Hello @d4k0,
we have been working on Torpedo and resolved the issue. It will be included in the next update of Torpedo and is currently in the master branch of this github repository.
Thank you for your notification!

**Comment by d4k0** [comment]
@philheller 
Thanks for the fix. Has the new version already been submitted to the Mozilla add-on store?

**Comment by philheller** [comment]
We are submitting the update within the next few days.

**Comment by d4k0** [comment]
@philheller 
Sorry to post again, but is there any news on this yet? 3.0.1 is still the latest version in the store.

**Comment by philheller** [comment]
The latest version was added to the store and is reviewed. It should be online any time now!
Sorry for the inconvenience.
