### ISSUE TITLE
Link detection not working in all cases

### ISSUE THREAD

**Issue by bitkleberAST** [SecUSo/torpedo#2]
I received an email that contains a link which is not recognized by the addin.
I looked at the code of the email and sow the following line:
bla... http://www.example.com/ www.example.com bla...

Some lines down there was a hyperlink like this, which was recognized correctly:
bla... http://example.com/somepage.html bla...

**Comment by bettyballin** [comment]
Thank you for reporting this issue. It will be fixed in the next update.
