### ISSUE TITLE
Changelog afer update is empty

### ISSUE THREAD

**Issue by beerisgood** [SecUSo/torpedo#4]
After automatic addons update, no changelog for this addon is available:
![torpedo](https://user-images.githubusercontent.com/9625159/31052964-317f9dee-a692-11e7-85da-88d77563e262.png)

Thunderbird 52.3.0 x86 - Windows 7 x64

**Comment by beerisgood** [comment]
Problem still exist:
![torpedo](https://user-images.githubusercontent.com/9625159/49647327-6e3b1d00-fa22-11e8-8683-6ccc181cffa9.png)

**Comment by philheller** [comment]
Thank you for your feedback.
We have been working on improving our version log and will continue to do so in the future.
