### ISSUE TITLE
Link to homepage is outdated

### ISSUE THREAD

**Issue by beerisgood** [SecUSo/torpedo#6]
On https://github.com/SecUSo/torpedo the link to your [website](https://www.secuso.informatik.tu-darmstadt.de/en/secuso/research/results/torpedo/) is outdated.

New one: https://secuso.aifb.kit.edu/TORPEDO.php

**Comment by beerisgood** [comment]
*push*

2 months later.
@SecUSo

**Comment by beerisgood** [comment]
@SecUSo problem still exist

**Comment by mghiglieri** [comment]
Thanks. Has been updated.
